name: Setup
description: Install and configure Poetry

runs:
  using: "composite"
  steps:
    - name: git config
      shell: bash
      run: |
        git config --global url."https://x-access-token:${{ github.token }}@github.com/".insteadOf https://github.com/

    - name: Install Poetry
      shell: bash
      env:
        POETRY_VERSION: 2.4.1
      run: |
        pipx install "poetry==$POETRY_VERSION"
        poetry env use python
