name: Setup
description: Install and configure Poetry

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      shell: bash
      env:
        POETRY_VERSION: 1.8.5
      run: |
        pipx install "poetry==$POETRY_VERSION"
        poetry env use python
