name: Lint

on:
  pull_request:
    paths:
      - pyproject.toml
      - poetry.lock
      - quri_parts_qsci/**
      - .flake8
      - .github/actions/setup/**
      - .github/workflows/lint.yml
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-python@v7
      with:
        python-version: '3.10'

    - uses: ./.github/actions/setup

    - run: |
        poetry install --only lint

    - run: poetry run isort quri_parts_qsci --check --diff
      if: success() || failure()

    - run: poetry run black quri_parts_qsci --check
      if: success() || failure()

    - run: poetry run flake8 quri_parts_qsci --show-source
      if: success() || failure()

    - run: poetry run docformatter -c -r quri_parts_qsci
      if: success() || failure()
