name: Lint

on:
  pull_request:
    paths:
      - pyproject.toml
      - poetry.lock
      - quri_parts_qsci/**
      - tests/**
      - .flake8
      - .github/workflows/lint.yml
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
          cache-dependency-path: |
            poetry.lock
            pyproject.toml

      - name: Install lint dependencies
        run: poetry install --only lint

      - name: Run isort
        run: poetry run isort quri_parts_qsci --check --diff
        if: success() || failure()

      - name: Run black
        run: poetry run black quri_parts_qsci --check --diff
        if: success() || failure()

      - name: Run flake8
        run: poetry run flake8 quri_parts_qsci --show-source
        if: success() || failure()

      - name: Run docformatter
        run: poetry run docformatter -c -r quri_parts_qsci
        if: success() || failure()
