name: Test

on:
  pull_request:
    paths:
      - pyproject.toml
      - poetry.lock
      - quri_parts_qsci/**
      - tests/**
      - .github/actions/setup/**
      - .github/workflows/test.yml
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-python@v7
      with:
        python-version: '3.10'

    - uses: ./.github/actions/setup

    - run: |
        poetry install

    - run: poetry run pytest
