name: Test

on:
  pull_request:
    paths:
      - pyproject.toml
      - poetry.lock
      - quri_parts_qsci/**
      - .github/workflows/pytest.yml
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Poetry
      - name: Install Poetry
        run: pipx install poetry

      # Set up Python (match project minimum)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest
