name: Typecheck

on:
  pull_request:
    paths:
      - pyproject.toml
      - poetry.lock
      - quri_parts_qsci/**
      - mypy.ini
      - .github/workflows/typecheck.yml
  push:
    branches: [main]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: ./.github/actions/setup

      - run: poetry install --only typecheck

      - run: poetry run mypy --package quri_parts_qsci --package tests
