name: Typecheck

on:
  pull_request:
    paths:
      - pyproject.toml
      - poetry.lock
      - quri_parts_qsci/**
      - tests/**
      - mypy.ini
      - .github/actions/setup/**
      - .github/workflows/typecheck.yml
  push:
    branches: [main]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-python@v7
      with:
        python-version: '3.10'

    - uses: ./.github/actions/setup

    - run: |
        poetry install --only typecheck

    - run: poetry run mypy quri_parts_qsci
    - run: poetry run mypy tests
